env:
  browser: true
  es6: true
extends:
  - "plugin:react/recommended"
  - airbnb
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  react/react-in-jsx-scope: 'off'
  react/jsx-filename-extension:
  - 1
  - extensions:
    - ".js"
    - ".jsx"
  react/display-name: 1
  react/jsx-props-no-spreading: 0
